config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'tops#login'
  post '/login', to: 'tops#create'
  delete '/logout', to: 'tops#destroy'
  get '/tops/main'
  root to: 'users#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password

  validates :uid, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= Person.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
  end
  def login
  end

  def create
    @user = Person.find_by(uid: session_params[:uid])

    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to tops_main_url, notice: 'ログインしました。'
    else
      render :login
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:uid, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @persons = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(user_params)

    if @person.save
      redirect_to new_user_path, notice: "ユーザーを登録しました。"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:person).permit(:uid, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ll4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to 'ユーザー登録', new_user_path , class: 'nav-link' %></li>
        <% if current_user %>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, class: 'nav-link'%></li>
        <% else %>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link'%></li>
        <% end %>
      </ul>
    </header>

    <%= yield %>
  </body>
</html>

app/views/tops/login.html.erb
<h1>ログイン</h1>

<%= form_with scope: :session, local:  true do |f|%>
  <div class="form-group">
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid, class: 'form-control', id: 'session_uid'%></div>
  <div class="form-group">
  <%= f.label :password, 'パスワード' %>
  <%= f.password_field :password, class: 'form-control', id: 'session_password'%></div>
  <%= f.submit 'ログインする', class: 'btn btn-primary'%>
<% end %>

app/views/tops/main.html.erb
<h1>ログイン成功</h1>

<div class="nav-item">
  <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
</div>

app/views/users/_form.html.erb
<%= form_for @person, url:  {action: :create} do |f| %>
  <div class="form-group">
    <%= f.label :uid, 'ユーザーID'%>
    <%= f.text_field :uid, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード'%>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>このアプリについて</h1>
<p>ユーザーIDとパスワードを登録することでログインできます。</p>

<p>testユーザーの方は、ユーザーID：kindai パスワード：passwordを入力ください。</p>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= render partial: 'form', locals: { person: @person} %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>